# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/BlacklistingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class BlacklistingReasonUi(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 224)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 190, 381, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("font-size:16px;\n"
"text-decoration:underline;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.blacklistReason = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.blacklistReason.setStyleSheet("border-radius:5px;\n"
"margin:10px;\n"
"background-color:rgba(255,255,255,0.5);\n"
"padding-left:3px;\n"
"color:black;\n"
"font-size:17px;\n"
"")
        self.blacklistReason.setObjectName("blacklistReason")
        self.verticalLayout.addWidget(self.blacklistReason)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Reason for blacklisting"))
        self.label.setText(_translate("Dialog", "Please enter reason for blacklisting"))
