# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LoginUi(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(402, 351)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pages = QtWidgets.QStackedWidget(Login)
        self.pages.setStyleSheet("QPushButton[accessibleName = \'link\'] {\n"
"    background:none;\n"
"    border:none;\n"
"    text-decoration:underline;\n"
"    color:blue;\n"
"    font-style:italic;\n"
"}\n"
"QPushButton[accessibleName = \'link\']:hover{\n"
"    color: red;\n"
"    font-size:13px;\n"
"}")
        self.pages.setObjectName("pages")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.loginPage)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_7 = QtWidgets.QLabel(self.loginPage)
        self.label_7.setMaximumSize(QtCore.QSize(128, 128))
        self.label_7.setStyleSheet("image:url(:images/user.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_30.addWidget(self.label_7)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.formFrame = QtWidgets.QFrame(self.loginPage)
        self.formFrame.setStyleSheet("QLineEdit {\n"
"    border-radius:5px;\n"
"    margin:0px;\n"
"    background-color:rgba(255,255,255,0.5);\n"
"    padding-left:3px;\n"
"    color:black;\n"
"    font-size:16px;\n"
"}\n"
"")
        self.formFrame.setObjectName("formFrame")
        self.formLayout = QtWidgets.QFormLayout(self.formFrame)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.formLayout.setContentsMargins(19, 12, 20, -1)
        self.formLayout.setVerticalSpacing(22)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formFrame)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.loginLibNo = QtWidgets.QLineEdit(self.formFrame)
        self.loginLibNo.setObjectName("loginLibNo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.loginLibNo)
        self.label_2 = QtWidgets.QLabel(self.formFrame)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.loginPassword = QtWidgets.QLineEdit(self.formFrame)
        self.loginPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.loginPassword.setObjectName("loginPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.loginPassword)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.formFrame)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.errorLabel = QtWidgets.QLabel(self.loginPage)
        self.errorLabel.setStyleSheet("")
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.horizontalLayout_3.addWidget(self.errorLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(self.loginPage)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.btnToSignup = QtWidgets.QPushButton(self.loginPage)
        self.btnToSignup.setMinimumSize(QtCore.QSize(60, 0))
        self.btnToSignup.setStyleSheet("")
        self.btnToSignup.setAutoDefault(False)
        self.btnToSignup.setObjectName("btnToSignup")
        self.horizontalLayout.addWidget(self.btnToSignup)
        self.btnLogin = QtWidgets.QPushButton(self.loginPage)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/enter.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btnLogin.setIcon(icon)
        self.btnLogin.setDefault(False)
        self.btnLogin.setObjectName("btnLogin")
        self.horizontalLayout.addWidget(self.btnLogin)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.pages.addWidget(self.loginPage)
        self.signupPage = QtWidgets.QWidget()
        self.signupPage.setObjectName("signupPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.signupPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_8 = QtWidgets.QLabel(self.signupPage)
        self.label_8.setMaximumSize(QtCore.QSize(128, 128))
        self.label_8.setStyleSheet("image:url(:images/user.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_31.addWidget(self.label_8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_31)
        self.formFrame1 = QtWidgets.QFrame(self.signupPage)
        self.formFrame1.setStyleSheet("QLineEdit {\n"
"    border-radius:5px;\n"
"    margin:0px;\n"
"    background-color:rgba(255,255,255,0.5);\n"
"    padding-left:3px;\n"
"    color:black;\n"
"    font-size:16px;\n"
"}\n"
"")
        self.formFrame1.setObjectName("formFrame1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formFrame1)
        self.formLayout_2.setContentsMargins(10, 20, 12, 20)
        self.formLayout_2.setVerticalSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_4 = QtWidgets.QLabel(self.formFrame1)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.signupLibNo = QtWidgets.QLineEdit(self.formFrame1)
        self.signupLibNo.setObjectName("signupLibNo")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.signupLibNo)
        self.label_5 = QtWidgets.QLabel(self.formFrame1)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formFrame1)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.signupNewPassword = QtWidgets.QLineEdit(self.formFrame1)
        self.signupNewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.signupNewPassword.setObjectName("signupNewPassword")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.signupNewPassword)
        self.signupConfirmPassword = QtWidgets.QLineEdit(self.formFrame1)
        self.signupConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.signupConfirmPassword.setObjectName("signupConfirmPassword")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.signupConfirmPassword)
        self.verticalLayout_4.addWidget(self.formFrame1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lblSignUpError = QtWidgets.QLabel(self.signupPage)
        self.lblSignUpError.setObjectName("lblSignUpError")
        self.horizontalLayout_5.addWidget(self.lblSignUpError)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label_9 = QtWidgets.QLabel(self.signupPage)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.btnToLogin = QtWidgets.QPushButton(self.signupPage)
        self.btnToLogin.setMinimumSize(QtCore.QSize(60, 60))
        self.btnToLogin.setStyleSheet("")
        self.btnToLogin.setAutoDefault(False)
        self.btnToLogin.setObjectName("btnToLogin")
        self.horizontalLayout_4.addWidget(self.btnToLogin)
        self.signUp = QtWidgets.QPushButton(self.signupPage)
        self.signUp.setDefault(True)
        self.signUp.setObjectName("signUp")
        self.horizontalLayout_4.addWidget(self.signUp)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.pages.addWidget(self.signupPage)
        self.verticalLayout_2.addWidget(self.pages)

        self.retranslateUi(Login)
        self.pages.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Dialog"))
        self.label.setText(_translate("Login", "Lib NO: "))
        self.loginLibNo.setPlaceholderText(_translate("Login", "library number"))
        self.label_2.setText(_translate("Login", "Password:"))
        self.loginPassword.setPlaceholderText(_translate("Login", "Password"))
        self.label_3.setText(_translate("Login", "<html><head/><body><p>dont have an account? </p></body></html>"))
        self.btnToSignup.setAccessibleName(_translate("Login", "link"))
        self.btnToSignup.setText(_translate("Login", "Sign up"))
        self.btnLogin.setText(_translate("Login", "Log In"))
        self.label_4.setText(_translate("Login", "Lib No:"))
        self.signupLibNo.setPlaceholderText(_translate("Login", "lib no"))
        self.label_5.setText(_translate("Login", "New password:"))
        self.label_6.setText(_translate("Login", "Confirm password:"))
        self.signupNewPassword.setPlaceholderText(_translate("Login", "New Password"))
        self.signupConfirmPassword.setPlaceholderText(_translate("Login", "Confirm Password"))
        self.lblSignUpError.setText(_translate("Login", "Password did not match"))
        self.label_9.setText(_translate("Login", "<html><head/><body><p>already have an account? </p></body></html>"))
        self.btnToLogin.setAccessibleName(_translate("Login", "link"))
        self.btnToLogin.setText(_translate("Login", "log in"))
        self.signUp.setText(_translate("Login", "Sign up"))
