# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/passwordchange.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PasswordChangeUi(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(387, 173)
        Dialog.setStyleSheet("* {\n"
"    font-size: 16px;\n"
"}\n"
"QLineEdit {\n"
"    border-radius:5px;\n"
"    background-color:rgba(255,255,255,0.5);\n"
"    padding-left:3px;\n"
"    color:black;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.changeNewPassword = QtWidgets.QLineEdit(Dialog)
        self.changeNewPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.changeNewPassword.setObjectName("changeNewPassword")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.changeNewPassword)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.changeConfirmPassword = QtWidgets.QLineEdit(Dialog)
        self.changeConfirmPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.changeConfirmPassword.setObjectName("changeConfirmPassword")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.changeConfirmPassword)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.changeOldPassword = QtWidgets.QLineEdit(Dialog)
        self.changeOldPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.changeOldPassword.setObjectName("changeOldPassword")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.changeOldPassword)
        self.verticalLayout.addLayout(self.formLayout)
        self.changePasswordError = QtWidgets.QLabel(Dialog)
        self.changePasswordError.setText("")
        self.changePasswordError.setObjectName("changePasswordError")
        self.verticalLayout.addWidget(self.changePasswordError)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.btnChangePassword = QtWidgets.QPushButton(Dialog)
        self.btnChangePassword.setObjectName("btnChangePassword")
        self.horizontalLayout.addWidget(self.btnChangePassword)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.changeOldPassword, self.changeNewPassword)
        Dialog.setTabOrder(self.changeNewPassword, self.changeConfirmPassword)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Change password"))
        self.label.setText(_translate("Dialog", "New password:"))
        self.changeNewPassword.setPlaceholderText(_translate("Dialog", "new password"))
        self.label_2.setText(_translate("Dialog", "Confirm password:"))
        self.changeConfirmPassword.setPlaceholderText(_translate("Dialog", "confirm new password"))
        self.label_4.setText(_translate("Dialog", "Old password:"))
        self.changeOldPassword.setPlaceholderText(_translate("Dialog", "Enter old password"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.btnChangePassword.setText(_translate("Dialog", "Ok"))
