# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/updateprofile.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UpdateProfileUi(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(400, 347)
        Dialog.setStyleSheet("* {\n"
"    font-size: 16px;\n"
"}\n"
"QLineEdit {\n"
"    border-radius:5px;\n"
"    background-color:rgba(255,255,255,0.5);\n"
"    padding-left:3px;\n"
"    color:black;\n"
"}\n"
"")
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setMaximumSize(QtCore.QSize(128, 128))
        self.label_7.setStyleSheet("image:url(:images/user.png);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_30.addWidget(self.label_7)
        self.verticalLayout_10.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.lblUserName = QtWidgets.QLabel(Dialog)
        self.lblUserName.setMaximumSize(QtCore.QSize(1600, 16777215))
        self.lblUserName.setText("")
        self.lblUserName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblUserName.setObjectName("lblUserName")
        self.horizontalLayout_31.addWidget(self.lblUserName)
        self.verticalLayout_10.addLayout(self.horizontalLayout_31)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setVerticalSpacing(15)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_33 = QtWidgets.QLabel(Dialog)
        self.label_33.setObjectName("label_33")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.label_34 = QtWidgets.QLabel(Dialog)
        self.label_34.setObjectName("label_34")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.label_35 = QtWidgets.QLabel(Dialog)
        self.label_35.setObjectName("label_35")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.label_36 = QtWidgets.QLabel(Dialog)
        self.label_36.setObjectName("label_36")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.updateFName = QtWidgets.QLineEdit(Dialog)
        self.updateFName.setObjectName("updateFName")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.updateFName)
        self.updateSName = QtWidgets.QLineEdit(Dialog)
        self.updateSName.setObjectName("updateSName")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.updateSName)
        self.updateOName = QtWidgets.QLineEdit(Dialog)
        self.updateOName.setObjectName("updateOName")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.updateOName)
        self.updatePhone = QtWidgets.QLineEdit(Dialog)
        self.updatePhone.setObjectName("updatePhone")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.updatePhone)
        self.verticalLayout_10.addLayout(self.formLayout_6)
        self.verticalLayout_10.setStretch(0, 1)
        self.verticalLayout.addLayout(self.verticalLayout_10)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.btnUpdateProfile = QtWidgets.QPushButton(Dialog)
        self.btnUpdateProfile.setObjectName("btnUpdateProfile")
        self.horizontalLayout.addWidget(self.btnUpdateProfile)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.pushButton_2.clicked.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Update Profile"))
        self.label_33.setText(_translate("Dialog", "First Name:"))
        self.label_34.setText(_translate("Dialog", "Second Name:"))
        self.label_35.setText(_translate("Dialog", "Other Name:"))
        self.label_36.setText(_translate("Dialog", "Phone Number:"))
        self.pushButton_2.setText(_translate("Dialog", "Cancel"))
        self.btnUpdateProfile.setText(_translate("Dialog", "Save"))
